CONTRIBUTING.md
LICENSE.md

- Adds the PolyForm NonCommercial license
- Adds first draft of our 'Contributor License Compromise'
it should be accompanied by
- a PR template that has a simple [ ] checkbox for contributors to acknowledge their awareness and compliance with our CLC
- a github action that ensures the checkbox has been checked in PRs made by non-team members.
---
For precedence, see for example CrabNebula's [devtools](https://github.com/crabnebula-dev/devtools?tab=License-1-ov-file).

Add license

---

src/routes/auth/v1/account/+page.server.ts
src/routes/auth/v1/account/+page.svelte
src/routes/auth/v1/oidc/logout/+page.svelte

Giving the ability for users to connect their SSO after creating accounts using passwords, simply by going to the account page and click the button "Link my account with [provider]"
^ Example with google as a provider

feat: connect SSO after login (closes #52)

---

src/lib/components/layouts/DefaultLayout.svelte

fix: ensure the footer always stays at the bottom

---

src/routes/+page.svelte

This PR removes emojis from card titles on the landing page and moves the "milk and honey" emojis below the cards based on feedback from Erlend.
Before: 
After:

UX: landing page iteration

---

src/routes/(app)/auth/v1/account/+page.svelte

Enable the dissociation of an external authentication provider for users who have previously linked both password and provider credentials

feat: unlink from provider

---

.dprint.jsonc
.eslintrc.cjs
.github/workflows/lint.yaml
.prettierignore
.typos.toml
Dockerfile
LICENSE.md
backend/Cargo.toml
backend/Dockerfile
backend/gdata/Cargo.toml
backend/gdata/gdata_explorer/Cargo.toml
backend/weird/src/profile.rs
deploy/rauthy/Dockerfile
justfile
package.json
src/app.css
src/lib/spow/spow-wasm.d.ts
src/lib/spow/spow-wasm.js
src/lib/spow/spow-wasm_bg.js
src/lib/spow/spow-wasm_bg.wasm.d.ts
src/routes/(app)/auth/v1/oidc/authorize/+page.svelte
src/routes/(app)/auth/v1/oidc/logout/+page.svelte
src/routes/(app)/auth/v1/providers/callback/+page.svelte
src/routes/(app)/feedback/+page.svelte
src/routes/(app)/feedback/confirmation/+page.svelte
svelte.config.js
vite.config.ts

Hi, there.
I've found some inconsistencies in the code. So, perhaps this PR will solve the issue.
This PR adds:
- [typos by crate-ci](https://github.com/crate-ci/typos), to fix and check for typos.
- [dprint by dprint](https://github.com/dprint/dprint), to properly format markdown, YAML, and Dockerfile files.
The mentioned tools are also included inside the `justfile`. So, one is able to check locally just using `just fmt` or `just fmt-check`.
The repo had `prettier` and `eslint` already, but it seems they were not used in previous commits. So, I have added both to CI and the just recipe too.
I use `ci:` as the commit prefix here. If these commits should belong under a different category, I'd be happy to change it.
One last step is fixing the error that comes from `eslint`:
```
Oops! …
```

Add CI to lint the codebase       

---

CONTRIBUTING.md
backend/gdata/Cargo.toml
justfile

I also changed the markdown link to reference-style links, which are much more readable.
Some parts are taken from [Axum Contribution Guide](https://github.com/tokio-rs/axum/blob/main/CONTRIBUTING.md) which is MIT-Licensed.

docs: update contributing guide

---

src/routes/(app)/u/[username]/mastodon/+page.svelte

Fixes the incorrect Mastodon `links` hyperlink, which was retrieved from Mastodon's API, by implementing a parser function specifically designed to extract the correct link directly.

fix: broken mastodon links

---

src/routes/(app)/auth/v1/account/+page.server.ts

Fixing the bug of #93: When the username is not defined, the website redirects the user to a 404 page (`http://.(public page)/pubpage-auth-callback?token=(token)`)

fix: user is redirected to a 404 page when username and custom domain is not set

---

src/lib/components/pubpage-admin/edit-links.svelte
src/lib/themes/minimal.svelte

Making the pubpage fully customizable by adding the inline editing feature for tags, links, and working capacity. The links editor was implemented with a dedicated modal form, while tags and working capacity were made editable using the `contenteditable` and `bind:value` features.

feat: inline-editing for tags, links and working capacity

---

src/lib/components/layouts/DefaultLayout.svelte

fix: improve accessibility

---

backend/weird/src/profile.rs

The resized avatar was accidentally discarded instead of being used.

fix: fix avatar resizing.

---

.github/workflows/check-for-clc.yaml
ARCHITECTURE.md
Cargo.toml
README.md
deploy/rauthy/deploy.sh
leaf/leaf-protocol/README.md
leaf/leaf-protocol/src/lib.rs
leaf/ts/README.md
leaf/ts/package.json

Some infrastructure (like CI and crates.io) will break if GitHub's automated routing stops working and we don't update our organization name in the codebase.
I haven't updated the name of our matrix channel. Is it still the same? @erlend-sh 
```
✦ 🦄 rg commune
README.md
87:If you want to chat about Weird and our vision for it feel free to join our [Discord Server](https://discord.gg/mbQYgFVBQx) or our bridge [Matrix Space](https://matrix.to/#/#discord:commune.sh).
```

docs: update outdated org name

---

README.md

Makes it easier to find on crates.io.

docs: add `leaf-protocol` badge

---

CONTRIBUTING.md
leaf/leaf-protocol/src/lib.rs
leaf/leaf-rpc-proto/src/lib.rs
leaf/leaf-rpc-server/src/proto.rs
leaf/ts/index.ts
src/lib/leaf/index.ts
src/lib/utils/databaseDump.ts
src/routes/(app)/[username]/+page.svelte
src/routes/(app)/[username]/[slug]/+page.server.ts
src/routes/(app)/[username]/new/+page.server.ts
src/routes/(app)/[username]/new/+page.svelte
src/routes/(internal)/__internal__/admin/+layout.server.ts
src/routes/(internal)/__internal__/admin/+page.svelte
src/routes/(internal)/__internal__/admin/database-dump/+page.server.ts
src/routes/(internal)/__internal__/admin/explorer/[[namespace]]/[[subspace]]/[[entityPath]]/+page.server.ts
src/routes/(internal)/__internal__/admin/explorer/[[namespace]]/[[subspace]]/[[entityPath]]/+page.svelte
src/routes/(internal)/__internal__/admin/update-username-domains/+page.server.ts
vite.config.ts

Adds a primitive admin explorer to the admin tools:
`http://localhost:9523/__internal__/admin/explorer`
- **why we needed it:** There was a bug that allowed you to put slashes in the page slugs, causing a situation where it was impossible to navigate to the page and delete it. This meant we had to have a way, as an admin, to go straight to the data and delete the offending page, so that the user wasn't stuck with the broken page eternally in their listing. We may have to do other, similar kinds of edits over time, so this will enable us to take quick action to fix problems instead of having to produce a migration in code and re-deploy before being able to fix the issue.
- **what it does:** Adds a new page to the admin tools that allows you to see all of the entities in the data and read / …

feat: add admin data explorer.

---

leaf/LICENSE.md

The README in the protocol folder should also me moved up to this space, with a header + link to this license file, as well as links to your leaf writings thus far @zicklag

Create LICENSE.md for /leaf

---

.editorconfig

editorconfig is widely supported in most popular editors today, it helps writing code in different file extensions without having to update editor configuration by hand.
This PR provides an editorconfig for TypeScript and Svelte to use tabs for indentation of size 2 and in general use EOL line feed with newline.

chore: introduce a `.editorconfig` for TypeScript/Svelte

---

src/lib/components/layouts/OuterLayout.svelte
src/lib/components/social-media/social-media-button.svelte
src/routes/(app)/[username]/+page.svelte
src/routes/(app)/[username]/[slug]/+page.svelte

Closes #259 
User Main Page
User page

style: app user pages

---

src/routes/(app)/[username]/+page.svelte

Refactor `SocialMediaButton` to make icons optional, and use them for the pages buttons. This also fixes the gap issues.
**Before**
**After**

style: fix user pages links gap

---

src/app.css

For reasons I don't understand dragging elements from svelte-sortable-list seems to break when it's parent has a `backdrop-filter`.

fix (app): Fix list elements jumping out of position when dragged

---

src/lib/types/embed-sdk.d.ts
src/lib/utils/markdown.ts
src/routes/(app)/[username]/[slug]/+page.server.ts
src/routes/(app)/[username]/[slug]/+page.svelte

Adds link previews to articles. (closes #241)

feat: link previews

---

src/lib/components/editors/PagesListEditor.svelte
src/routes/(app)/[username]/+page.svelte

Frontend UI to reorder pages while editing user profiles

feat: reorder pages in user profile

---

src/routes/(app)/[username]/+layout.svelte

fixes layout issues for signed in user's sidebar:
- sidebar always extends fully, even if the content inside is empty
- expands the main section to always be its max possible width. (no edit button overlapping)

fix: sidebar layout styles

---

src/lib/themes/reader/page.jinja
src/lib/themes/reader/profile.jinja

Adds a new theme, Reader, with a minimalist, but customizable sytle.

feat: add Reader theme
