muni-town/weird

- ARCHITECTURE.md
- backend/gdata/gdata_explorer/src/main.rs
- backend/src/auth.rs
- backend/weird/src/lib.rs
- docs/login-with-weird.md
Thanks to https://github.com/crate-ci/typos/
> docs: fix typos

- src/routes/auth/v1/account/+page.svelte
- src/routes/u/[username]/+page.svelte
Fix double links and descriptions in the members card and saving profile deleting mastodon username bugs
> fix: buggy mastodon profile

- backend/weird/src/profile.rs
- src/lib/rauthy/index.ts
- src/routes/(app)/account/link-mastodon/+page.server.ts
- src/routes/(app)/account/link-mastodon/+page.svelte
- src/routes/(app)/account/update/+page.server.ts
- src/routes/(app)/auth/v1/account/+page.server.ts
- src/routes/(app)/auth/v1/account/+page.svelte
- src/routes/(app)/u/[username]/+page.svelte
- src/routes/(app)/u/[username]/mastodon/+page.server.ts
- src/routes/(app)/u/[username]/mastodon/+page.svelte
Adding a search function that utilizes Mastodon's API to explore content in users' statuses.
> feat: mastodon posts searching system

- src/lib/themes/minimal.svelte
Fixed incorrect protocol for inline editing post target
> fix: incorrect inline editing post target

- backend/weird/src/lib.rs
- backend/weird/src/profile.rs
- src/routes/(app)/u/[username]/mastodon/+page.svelte
As the user profile is accessible publicly through Iroh, this makes mastodon_access_token accessible to everyone. This PR sets every mastodon_access_token to Null and substitute the usage of mastodon_access_token
> fix: publicly accesible mastodon access token through iroh

- .env.local
- CONTRIBUTING.md
- compose.local.yaml
Credits to @zicklag for providing the compose file.
> docs: fully containerized setup

- src/routes/(app)/[username]/[slug]/+page.server.ts
- src/routes/(app)/[username]/[slug]/+page.svelte
- src/routes/(app)/[username]/[slug]/components/Content.svelte
- src/routes/(app)/[username]/[slug]/components/Header.svelte
- src/routes/(app)/[username]/[slug]/components/Links.svelte
- src/routes/(app)/[username]/[slug]/components/Page.svelte
> refactor: (app)-username-slug route

- src/routes/(app)/account/register/confirmation/+page.svelte
- src/routes/(app)/account/register/confirmation/components/ConfirmationPage.svelte
- src/routes/(app)/account/register/confirmation/components/SuccessMessage.svelte
> refactor: update (app)-account-register-confirmation to new theming pattern

- src/routes/(app)/claim-username/+page.svelte
- src/routes/(app)/claim-username/components/ClaimUsernameForm.svelte
- src/routes/(app)/claim-username/components/ClaimUsernamePage.svelte
> refactor: update (app)-claim-username to new theming pattern

- src/routes/(app)/feedback/confirmation/+page.svelte
- src/routes/(app)/feedback/confirmation/componenets/FeedbackPage.svelte
> refactor: update (app)-feedback-confirmation to new theming pattern

- src/routes/(app)/feedback/+page.svelte
- src/routes/(app)/feedback/components/FeedbackForm.svelte
- src/routes/(app)/feedback/components/FeedbackPage.svelte
> refactor: update (app)-feedback to new theming pattern

- src/routes/(app)/auth/v1/users/register/+page.svelte
- src/routes/(app)/auth/v1/users/register/components/RegisterForm.svelte
- src/routes/(app)/auth/v1/users/register/components/RegisterPage.svelte
> refactor: update (app)-auth-v1-users-register to new theming pattern.

- src/routes/(app)/login/+page.svelte
- src/routes/(app)/login/components/LoginForm.svelte
- src/routes/(app)/login/components/LoginPage.svelte
- src/routes/(app)/login/components/ProviderLoginButtons.svelte
This is part of https://github.com/muni-town/weird/issues/187, more details can be found there.
> refactor: update (app)-login to new theming pattern.

- CONTRIBUTING.md
- DEVELOPER.md
- justfile
Detailed documentation for developers and also a couple recipes for Justfile for docker environment management.
> docs: update documentation for developers.

- src/lib/components/editors/LinksEditor.svelte
- src/lib/utils/import-opml.ts
Allow the user to import links directly from OPML files. Issue:
- #213
> feat: import links from OPML files.

- src/lib/components/editors/CompositeMarkdownEditor.svelte
- src/routes/(app)/[username]/[slug]/+page.svelte
- src/routes/(app)/[username]/new/+page.svelte
> fix slug and removed click to edit btn

- src/routes/(app)/people/+page.server.ts
- src/routes/(app)/people/+page.svelte
> Added hashtag in url

- src/lib/leaf/profile.ts
Uses `update_components` over two calls, one for `add..` and other for `del..` in RPC call for `setProfile` procedure.
> feat: use `update_components` on `setProfile`

- package.json
- pnpm-lock.yaml
- src/lib/components/editors/LinksEditor.svelte
Prevents the last link entry, always blank inputs, from being sorted into the Links list while editing and removes the cleanup workaround that is no longer needed.
> feat(app): locks new link input on profile

- src/lib/utils/markdown.ts
Display full url in link previews
Fixes invalid `href` in links previews
> feat: display full url in link previews
